// Procedural rasterizer for the DocuLens document/lens mark. Pure math (no
// canvas/image library): each shape is a signed-distance function evaluated
// per pixel, composited with 1px-wide anti-aliasing. Deterministic — the same
// `size` always produces the same pixels, so output is regenerated by
// `generate-icons.mjs` rather than hand-edited.

const ACCENT = [67, 56, 202]; // #4338ca — apps/web/app/globals.css --color-accent
const WHITE = [255, 255, 255];

function sdBox(px, py, cx, cy, hw, hh, r) {
  const dx = Math.abs(px - cx) - hw + r;
  const dy = Math.abs(py - cy) - hh + r;
  const ax = Math.max(dx, 0);
  const ay = Math.max(dy, 0);
  return Math.sqrt(ax * ax + ay * ay) + Math.min(Math.max(dx, dy), 0) - r;
}

function sdCircle(px, py, cx, cy, radius) {
  return Math.hypot(px - cx, py - cy) - radius;
}

function sdSegment(px, py, ax, ay, bx, by) {
  const abx = bx - ax;
  const aby = by - ay;
  const apx = px - ax;
  const apy = py - ay;
  const t = Math.max(0, Math.min(1, (apx * abx + apy * aby) / (abx * abx + aby * aby)));
  const cx = ax + abx * t;
  const cy = ay + aby * t;
  return Math.hypot(px - cx, py - cy);
}

/** Coverage in [0, 1] for a shape boundary at distance `d`, edge-antialiased. */
function coverage(d, edge) {
  return Math.max(0, Math.min(1, 0.5 - d / edge));
}

/**
 * Renders the mark into an RGBA buffer of `size`x`size` pixels.
 *
 * Background: rounded-square accent fill (opaque — safe for Apple touch/
 * manifest tiles that must not rely on transparency).
 * Glyph: white document-with-lines + magnifying-glass stroke, matching the
 * header mark's proportions (apps/web/app/layout.tsx), simplified to a
 * single stroke weight that stays legible from 16px up.
 */
export function renderMark(size) {
  const buffer = new Uint8ClampedArray(size * size * 4);
  const edge = Math.max(1, size / 24); // ~1px anti-aliasing band, scaled up for tiny sizes

  const bgCx = size / 2;
  const bgCy = size / 2;
  const bgHalf = size / 2;
  const bgRadius = size * 0.22;

  const stroke = Math.max(1, size * 0.075);
  const strokeHalf = stroke / 2;

  // Document body: rounded rect outline.
  const docCx = size * 0.44;
  const docCy = size * 0.42;
  const docHw = size * 0.17;
  const docHh = size * 0.23;
  const docRadius = size * 0.05;

  // Two content lines inside the document.
  const line1Y = docCy - docHh * 0.35;
  const line2Y = docCy + docHh * 0.05;
  const lineX0 = docCx - docHw * 0.55;
  const lineX1 = docCx + docHw * 0.55;

  // Magnifying glass: ring + diagonal handle.
  const lensCx = size * 0.64;
  const lensCy = size * 0.66;
  const lensRadius = size * 0.15;
  const handleX0 = lensCx + lensRadius * 0.72;
  const handleY0 = lensCy + lensRadius * 0.72;
  const handleX1 = size * 0.82;
  const handleY1 = size * 0.84;

  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      const px = x + 0.5;
      const py = y + 0.5;

      const bgCoverage = coverage(sdBox(px, py, bgCx, bgCy, bgHalf, bgHalf, bgRadius), edge);
      if (bgCoverage <= 0) {
        continue; // fully transparent outside the rounded square
      }

      const docStroke = Math.abs(sdBox(px, py, docCx, docCy, docHw, docHh, docRadius)) - strokeHalf;
      const line1 = sdSegment(px, py, lineX0, line1Y, lineX1, line1Y) - strokeHalf;
      const line2 = sdSegment(px, py, lineX0, line2Y, lineX1, line2Y) - strokeHalf;
      const lensRing = Math.abs(sdCircle(px, py, lensCx, lensCy, lensRadius)) - strokeHalf;
      const handle = sdSegment(px, py, handleX0, handleY0, handleX1, handleY1) - strokeHalf;

      const glyphDistance = Math.min(docStroke, line1, line2, lensRing, handle);
      const glyphCoverage = coverage(glyphDistance, edge);

      const i = (y * size + x) * 4;
      // Composite white glyph over accent background, then apply the
      // background shape's own edge alpha for the rounded-square corners.
      const r = ACCENT[0] + (WHITE[0] - ACCENT[0]) * glyphCoverage;
      const g = ACCENT[1] + (WHITE[1] - ACCENT[1]) * glyphCoverage;
      const b = ACCENT[2] + (WHITE[2] - ACCENT[2]) * glyphCoverage;

      buffer[i] = r;
      buffer[i + 1] = g;
      buffer[i + 2] = b;
      buffer[i + 3] = Math.round(255 * bgCoverage);
    }
  }

  return buffer;
}
